scoreboard players random @s random 1 21
execute as @s[scores={random=1}] run setblock 0 63 0 minecraft:stone
execute as @s[scores={random=2}] run setblock 0 63 0 minecraft:grass
execute as @s[scores={random=3}] run setblock 0 63 0 minecraft:gravel
execute as @s[scores={random=4}] run setblock 0 63 0 minecraft:snow
execute as @s[scores={random=5}] run setblock 0 63 0 minecraft:andesite
execute as @s[scores={random=6}] run setblock 0 63 0 minecraft:diorite
execute as @s[scores={random=7}] run setblock 0 63 0 minecraft:granite
execute as @s[scores={random=8}] run setblock 0 63 0 minecraft:dirt
execute as @s[scores={random=9}] run setblock 0 63 0 minecraft:oak_log
execute as @s[scores={random=10}] run setblock 0 63 0 minecraft:spruce_log
execute as @s[scores={random=11}] run setblock 0 63 0 minecraft:coal_ore
execute as @s[scores={random=12}] run setblock 0 63 0 minecraft:birch_log
execute as @s[scores={random=13}] run setblock 0 63 0 minecraft:iron_ore
execute as @s[scores={random=14}] run setblock 0 63 0 minecraft:packed_ice
execute as @s[scores={random=15}] run setblock 0 63 0 minecraft:clay
execute as @s[scores={random=16}] run setblock 0 63 0 minecraft:dark_oak_log
execute as @s[scores={random=17}] run setblock 0 63 0 minecraft:podzol
execute as @s[scores={random=18}] run setblock 0 63 0 minecraft:melon_block
execute as @s[scores={random=19}] run setblock 0 63 0 minecraft:pumpkin
execute as @s[scores={random=20}] run setblock 0 63 0 minecraft:gold_ore
execute as @s[scores={random=21}] run setblock 0 63 0 minecraft:birch_log
