scoreboard players random @s random 1 37
execute as @s[scores={random=1}] run setblock 0 63 0 grass
execute as @s[scores={random=2}] run setblock 0 63 0 cobblestone
execute as @s[scores={random=3}] run setblock 0 63 0 stone
execute as @s[scores={random=4}] run setblock 0 63 0 mossy_cobblestone
execute as @s[scores={random=5}] run setblock 0 63 0 prismarine
execute as @s[scores={random=6}] run setblock 0 63 0 jungle_log
execute as @s[scores={random=7}] run setblock 0 63 0 sand
execute as @s[scores={random=8}] run setblock 0 63 0 gravel
execute as @s[scores={random=9}] run setblock 0 63 0 iron_ore
execute as @s[scores={random=10}] run setblock 0 63 0 coal_ore
execute as @s[scores={random=11}] run setblock 0 63 0 prismarine["prismarine_block_type"="bricks"]
execute as @s[scores={random=12}] run setblock 0 63 0 stone["stone_type"="diorite"]
execute as @s[scores={random=13}] run setblock 0 63 0 oak_log
execute as @s[scores={random=14}] run setblock 0 63 0 prismarine["prismarine_block_type"="dark"]
execute as @s[scores={random=15}] run setblock 0 63 0 snow
execute as @s[scores={random=16}] run setblock 0 63 0 stone["stone_type"="andesite"]
execute as @s[scores={random=17}] run setblock 0 63 0 stone["stone_type"="granite"]
execute as @s[scores={random=18}] run setblock 0 63 0 dirt
execute as @s[scores={random=19}] run setblock 0 63 0 clay
execute as @s[scores={random=20}] run setblock 0 63 0 spruce_log
execute as @s[scores={random=21}] run setblock 0 63 0 dark_oak_log
execute as @s[scores={random=22}] run setblock 0 63 0 birch_log
execute as @s[scores={random=23}] run setblock 0 63 0 redstone_ore
execute as @s[scores={random=24}] run setblock 0 63 0 gold_ore
execute as @s[scores={random=25}] run setblock 0 63 0 packed_ice
execute as @s[scores={random=26}] run setblock 0 63 0 sea_lantern
execute as @s[scores={random=27}] run setblock 0 63 0 coral_block["coral_color"="pink"]
execute as @s[scores={random=28}] run setblock 0 63 0 coral_block["coral_color"="yellow"]
execute as @s[scores={random=29}] run setblock 0 63 0 podzol
execute as @s[scores={random=30}] run setblock 0 63 0 sponge
execute as @s[scores={random=31}] run setblock 0 63 0 coral_block["coral_color"="red"]
execute as @s[scores={random=32}] run setblock 0 63 0 coral_block["coral_color"="blue"]
execute as @s[scores={random=33}] run setblock 0 63 0 coral_block["coral_color"="purple"]
execute as @s[scores={random=34}] run setblock 0 63 0 melon_block
execute as @s[scores={random=35}] run setblock 0 63 0 pumpkin
execute as @s[scores={random=36}] run setblock 0 63 0 diamond_ore
execute as @s[scores={random=37}] run setblock 0 63 0 birch_log
