scoreboard players random @s random 1 76
execute as @s[scores={random=1}] run setblock 0 63 0 minecraft:grass
execute as @s[scores={random=2}] run setblock 0 63 0 minecraft:quartz_block
execute as @s[scores={random=3}] run setblock 0 63 0 minecraft:cobblestone
execute as @s[scores={random=4}] run setblock 0 63 0 minecraft:stone
execute as @s[scores={random=5}] run setblock 0 63 0 minecraft:mossy_cobblestone
execute as @s[scores={random=6}] run setblock 0 63 0 minecraft:oak_log
execute as @s[scores={random=7}] run setblock 0 63 0 minecraft:sand
execute as @s[scores={random=8}] run setblock 0 63 0 minecraft:blackstone
execute as @s[scores={random=9}] run setblock 0 63 0 minecraft:netherrack
execute as @s[scores={random=10}] run setblock 0 63 0 minecraft:red_sand
execute as @s[scores={random=11}] run setblock 0 63 0 minecraft:red_sandstone
execute as @s[scores={random=12}] run setblock 0 63 0 minecraft:prismarine
execute as @s[scores={random=13}] run setblock 0 63 0 minecraft:iron_ore
execute as @s[scores={random=14}] run setblock 0 63 0 minecraft:jungle_log
execute as @s[scores={random=15}] run setblock 0 63 0 minecraft:coal_ore
execute as @s[scores={random=16}] run setblock 0 63 0 minecraft:gravel
execute as @s[scores={random=17}] run setblock 0 63 0 minecraft:redstone_ore
execute as @s[scores={random=18}] run setblock 0 63 0 minecraft:nether_bricks
execute as @s[scores={random=19}] run setblock 0 63 0 minecraft:soul_sand
execute as @s[scores={random=20}] run setblock 0 63 0 minecraft:prismarine_bricks
execute as @s[scores={random=21}] run setblock 0 63 0 minecraft:diorite
execute as @s[scores={random=22}] run setblock 0 63 0 minecraft:red_nether_bricks
execute as @s[scores={random=23}] run setblock 0 63 0 minecraft:basalt
execute as @s[scores={random=24}] run setblock 0 63 0 minecraft:terracotta
execute as @s[scores={random=25}] run setblock 0 63 0 minecraft:sandstone
execute as @s[scores={random=26}] run setblock 0 63 0 minecraft:dark_prismarine
execute as @s[scores={random=27}] run setblock 0 63 0 minecraft:gold_ore
execute as @s[scores={random=28}] run setblock 0 63 0 minecraft:snow
execute as @s[scores={random=29}] run setblock 0 63 0 minecraft:andesite
execute as @s[scores={random=30}] run setblock 0 63 0 minecraft:granite
execute as @s[scores={random=31}] run setblock 0 63 0 minecraft:dirt
execute as @s[scores={random=32}] run setblock 0 63 0 minecraft:clay
execute as @s[scores={random=33}] run setblock 0 63 0 minecraft:crimson_nylium
execute as @s[scores={random=34}] run setblock 0 63 0 minecraft:warped_nylium
execute as @s[scores={random=35}] run setblock 0 63 0 minecraft:magma_block
execute as @s[scores={random=36}] run setblock 0 63 0 minecraft:emerald_ore
execute as @s[scores={random=37}] run setblock 0 63 0 minecraft:red_terracotta
execute as @s[scores={random=38}] run setblock 0 63 0 minecraft:orange_terracotta
execute as @s[scores={random=39}] run setblock 0 63 0 minecraft:yellow_terracotta
execute as @s[scores={random=40}] run setblock 0 63 0 minecraft:brown_terracotta
execute as @s[scores={random=41}] run setblock 0 63 0 minecraft:acacia_log
execute as @s[scores={random=42}] run setblock 0 63 0 minecraft:spruce_log
execute as @s[scores={random=43}] run setblock 0 63 0 minecraft:lapis_ore
execute as @s[scores={random=44}] run setblock 0 63 0 minecraft:soul_soil
execute as @s[scores={random=45}] run setblock 0 63 0 minecraft:glowstone
execute as @s[scores={random=46}] run setblock 0 63 0 minecraft:dark_oak_log
execute as @s[scores={random=47}] run setblock 0 63 0 minecraft:birch_log
execute as @s[scores={random=48}] run setblock 0 63 0 minecraft:nether_quartz_ore
execute as @s[scores={random=49}] run setblock 0 63 0 minecraft:nether_wart_block
execute as @s[scores={random=50}] run setblock 0 63 0 minecraft:warped_wart_block
execute as @s[scores={random=51}] run setblock 0 63 0 minecraft:gilded_blackstone
execute as @s[scores={random=52}] run setblock 0 63 0 minecraft:shroomlight
execute as @s[scores={random=53}] run setblock 0 63 0 minecraft:light_gray_terracotta
execute as @s[scores={random=54}] run setblock 0 63 0 minecraft:white_terracotta
execute as @s[scores={random=55}] run setblock 0 63 0 minecraft:packed_ice
execute as @s[scores={random=56}] run setblock 0 63 0 minecraft:nether_gold_ore
execute as @s[scores={random=57}] run setblock 0 63 0 minecraft:sea_lantern
execute as @s[scores={random=58}] run setblock 0 63 0 minecraft:honeycomb_block
execute as @s[scores={random=59}] run setblock 0 63 0 minecraft:diamond_ore
execute as @s[scores={random=60}] run setblock 0 63 0 minecraft:brain_coral_block
execute as @s[scores={random=61}] run setblock 0 63 0 minecraft:horn_coral_block
execute as @s[scores={random=62}] run setblock 0 63 0 minecraft:podzol
execute as @s[scores={random=63}] run setblock 0 63 0 minecraft:sponge
execute as @s[scores={random=64}] run setblock 0 63 0 minecraft:obsidian
execute as @s[scores={random=65}] run setblock 0 63 0 minecraft:fire_coral_block
execute as @s[scores={random=66}] run setblock 0 63 0 minecraft:tube_coral_block
execute as @s[scores={random=67}] run setblock 0 63 0 minecraft:bubble_coral_block
execute as @s[scores={random=68}] run setblock 0 63 0 minecraft:melon_block
execute as @s[scores={random=69}] run setblock 0 63 0 minecraft:pumpkin
execute as @s[scores={random=70}] run setblock 0 63 0 minecraft:birch_log
execute as @s[scores={random=71}] run setblock 0 63 0 minecraft:slime_block
execute as @s[scores={random=72}] run setblock 0 63 0 minecraft:honey_block
execute as @s[scores={random=73}] run setblock 0 63 0 minecraft:ancient_debris
execute as @s[scores={random=74}] run setblock 0 63 0 minecraft:crying_obsidian
execute as @s[scores={random=75}] run setblock 0 63 0 minecraft:beehive
execute as @s[scores={random=76}] run setblock 0 63 0 minecraft:bee_nest
