scoreboard players random @s random 1 56
execute as @s[scores={random=1}] run summon pig 0 64 0
execute as @s[scores={random=2}] run summon cow 0 64 0
execute as @s[scores={random=3}] run summon sheep 0 64 0
execute as @s[scores={random=4}] run summon chicken 0 64 0
execute as @s[scores={random=5}] run summon mooshroom 0 64 0
execute as @s[scores={random=6}] run summon zombie 0 64 0
execute as @s[scores={random=7}] run summon rabbit 0 64 0
execute as @s[scores={random=8}] run summon spider 0 64 0
execute as @s[scores={random=9}] run summon creeper 0 64 0
execute as @s[scores={random=10}] run summon wolf 0 64 0
execute as @s[scores={random=11}] run summon stray 0 64 0
execute as @s[scores={random=12}] run summon fox 0 64 0
execute as @s[scores={random=13}] run summon polar_bear 0 64 0
execute as @s[scores={random=14}] run summon turtle 0 64 0
execute as @s[scores={random=15}] run summon squid 0 64 0
execute as @s[scores={random=16}] run summon drowned 0 64 0
execute as @s[scores={random=17}] run summon salmon 0 64 0
execute as @s[scores={random=18}] run summon tropicalfish 0 64 0
execute as @s[scores={random=19}] run summon guardian 0 64 0
execute as @s[scores={random=20}] run summon pufferfish 0 64 0
execute as @s[scores={random=21}] run summon cod 0 64 0
execute as @s[scores={random=22}] run summon elder_guardian 0 64 0
execute as @s[scores={random=23}] run summon dolphin 0 64 0
execute as @s[scores={random=24}] run summon parrot 0 64 0
execute as @s[scores={random=25}] run summon vex 0 64 0
execute as @s[scores={random=26}] run summon ocelot 0 64 0
execute as @s[scores={random=27}] run summon panda 0 64 0
execute as @s[scores={random=28}] run summon witch 0 64 0
execute as @s[scores={random=29}] run summon horse 0 64 0
execute as @s[scores={random=30}] run summon llama 0 64 0
execute as @s[scores={random=31}] run summon villager 0 64 0
execute as @s[scores={random=32}] run summon husk 0 64 0
execute as @s[scores={random=33}] run summon pillager 0 64 0
execute as @s[scores={random=34}] run summon wandering_trader 0 64 0
execute as @s[scores={random=35}] run summon donkey 0 64 0
execute as @s[scores={random=36}] run summon vindicator 0 64 0
execute as @s[scores={random=37}] run summon piglin 0 64 0
execute as @s[scores={random=38}] run summon magma_cube 0 64 0
execute as @s[scores={random=39}] run summon hoglin 0 64 0
execute as @s[scores={random=40}] run summon blaze 0 64 0
execute as @s[scores={random=41}] run summon strider 0 64 0
execute as @s[scores={random=42}] run summon wither_skeleton 0 64 0
execute as @s[scores={random=43}] run summon ghast 0 64 0
execute as @s[scores={random=44}] run summon bee 0 64 0
execute as @s[scores={random=45}] run summon cat 0 64 0
execute as @s[scores={random=46}] run summon slime 0 64 0
execute as @s[scores={random=47}] run summon mule 0 64 0
execute as @s[scores={random=48}] run summon skeleton 0 64 0
execute as @s[scores={random=49}] run summon phantom 0 64 0
execute as @s[scores={random=50}] run summon zombie_horse 0 64 0
execute as @s[scores={random=51}] run summon silverfish 0 64 0
execute as @s[scores={random=52}] run summon cave_spider 0 64 0
execute as @s[scores={random=53}] run summon witch 0 64 0
execute as @s[scores={random=54}] run summon endermite 0 64 0
execute as @s[scores={random=55}] run summon enderman 0 64 0
execute as @s[scores={random=56}] run summon shulker 0 64 0
